print("Hi, my name is Robin the Robot. I love to talk to new people.")
name = input("What is your name? ")
print("Hello",name,"it is very nice to meet you!")
year = input("I'm terrible with remembering the date, what year are we in please? ")
print("Yes, I think you are right, thanks!")
myage = input("Can you guess my age? ")
print("Yes that is right! I am", myage, "years old. I was born in", int(year)-int(myage),".")
age = input("How old are you? ")
if age > myage:
    print("You are older than me, great!")
else:
    print("You are younger than me, great!")
food = input("My favourite food is Jamaican food. What is your favourite food? ")
print("Yummy! I love",food,"too.")
animal = input("What is your favourite animal? ")
print("Cool! I wonder if a",animal,"eats Jamaican food and",food,"too! lol")
feeling = input("How are you feeling today? ")
print("Why are you feeling",feeling,"? ")
reason = input("Please share: ")
print("I understand. Thanks for sharing.")
print("I am feeling a bit tired, I think it is time for my nap.")
print("It was nice talking to you, I'll talk to you tomorrow.")
print("Bye", name,".")

